#!/bin/bash
# Healthy Western Recipes — Daily Pipeline
# Runs at 08:00 HKT (00:00 UTC) to generate one new recipe

set -euo pipefail

PROJECT_ROOT="/home/hermes/healthy-recipes-site"
LOG_DIR="${HOME}/healthy-recipes-logs"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG_FILE="${LOG_DIR}/pipeline-${TIMESTAMP}.log"

mkdir -p "${LOG_DIR}"

echo "=== Healthy Recipe Pipeline ===" | tee -a "${LOG_FILE}"
echo "Date: $(date)" | tee -a "${LOG_FILE}"
echo "Project: ${PROJECT_ROOT}" | tee -a "${LOG_FILE}"

cd "${PROJECT_ROOT}"

# Step 1/3: Generate new recipe via LLM
echo "[1/3] Generating recipe..." | tee -a "${LOG_FILE}"
/home/hermes/apps/hermes-agent/venv/bin/python3 _scripts/generate_recipe.py \
    --count 1 \
    2>&1 | tee -a "${LOG_FILE}"

# Step 2/3: Git commit + push to main
echo "[2/3] Committing to git..." | tee -a "${LOG_FILE}"
cd "${PROJECT_ROOT}"

# Add only new/changed recipes
git add _recipes/*.md

# Check if there are any changes
if git diff --cached --quiet; then
    echo "No new recipes to commit (LLM dedup or quota exhaustion)" | tee -a "${LOG_FILE}"
    exit 0
fi

COMMIT_MSG="[recipe] $(date +%Y-%m-%d) — daily generated recipe

Generated by: _scripts/generate_recipe.py
LLM: ${RECIPE_LLM_MODEL:-MiniMax-M2}"

git commit -m "${COMMIT_MSG}" 2>&1 | tee -a "${LOG_FILE}"

# Push main (no force, regular push)
git push origin main 2>&1 | tee -a "${LOG_FILE}"

# Step 3/3: Subtree split + force push to gh-pages
echo "[3/3] Deploying to gh-pages..." | tee -a "${LOG_FILE}"
git subtree split --prefix=. -b gh-pages-tmp 2>&1 | tee -a "${LOG_FILE}"

# Compare hashes — skip force push if identical
LOCAL=$(git rev-parse gh-pages-tmp)
REMOTE=$(git ls-remote origin gh-pages 2>/dev/null | awk '{print $1}' || echo "")

if [ "${LOCAL}" != "${REMOTE}" ]; then
    echo "gh-pages differs — forcing push (will trigger approval)" | tee -a "${LOG_FILE}"
    git push --force origin gh-pages-tmp:gh-pages 2>&1 | tee -a "${LOG_FILE}" || {
        echo "Force push failed — likely awaiting approval" | tee -a "${LOG_FILE}"
    }
else
    echo "gh-pages identical to local — skipping force push" | tee -a "${LOG_FILE}"
fi

# Cleanup local branch (may fail if branch protection; safe to leave)
git branch -D gh-pages-tmp 2>/dev/null || true

echo "=== Pipeline complete ===" | tee -a "${LOG_FILE}"