#!/bin/bash
# Healthy Western Recipes — Daily Pipeline
# Runs at 08:00 HKT (00:00 UTC) to generate one new recipe
#
# Updated 2026-09-02 by 惠惠 — P4 fix:
# - REMOVED `git subtree split --prefix=. -b gh-pages-tmp` (CF Pages auto-builds from main; gh-pages not needed)
# - REMOVED `git push --force origin gh-pages-tmp:gh-pages` (would trigger Hermes DANGEROUS_PATTERNS block)
# - REMOVED `git branch -D gh-pages-tmp` (cleanup of removed branch)
# - ADDED env loading from /home/hermes/.hermes/.env (cron does not inherit shell env)
# Simplified: generate recipe → commit → push main → CF Pages auto-build → live

set -euo pipefail

# Load env (cron context has no shell env, so explicitly source from Hermes .env)
# set -a exports every subsequently-defined variable; set +a stops it.
if [ -f /home/hermes/.hermes/.env ]; then
    set -a
    source /home/hermes/.hermes/.env
    set +a
fi

PROJECT_ROOT="/home/hermes/healthy-recipes-site"
LOG_DIR="${HOME}/healthy-recipes-logs"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG_FILE="${LOG_DIR}/pipeline-${TIMESTAMP}.log"

mkdir -p "${LOG_DIR}"

echo "=== Healthy Recipe Pipeline ===" | tee -a "${LOG_FILE}"
echo "Date: $(date)" | tee -a "${LOG_FILE}"
echo "Project: ${PROJECT_ROOT}" | tee -a "${LOG_FILE}"

cd "${PROJECT_ROOT}"

# Step 1/2: Generate new recipe via LLM
echo "[1/2] Generating recipe..." | tee -a "${LOG_FILE}"
/home/hermes/apps/hermes-agent/venv/bin/python3 _scripts/generate_recipe.py \
    --count 1 \
    2>&1 | tee -a "${LOG_FILE}"

# Step 2/2: Git commit + push to main (CF Pages auto-builds from main)
echo "[2/2] Committing to git..." | tee -a "${LOG_FILE}"
cd "${PROJECT_ROOT}"

# Add only new/changed recipes
git add _recipes/*.md

# Check if there are any changes
if git diff --cached --quiet; then
    echo "No new recipes to commit (LLM dedup or quota exhaustion)" | tee -a "${LOG_FILE}"
    exit 0
fi

COMMIT_MSG="[recipe] $(date +%Y-%m-%d) — daily generated recipe

Generated by: _scripts/generate_recipe.py
LLM: ${RECIPE_LLM_MODEL:-MiniMax-M2}"

git commit -m "${COMMIT_MSG}" 2>&1 | tee -a "${LOG_FILE}"

# Push main — CF Pages watches main branch and auto-builds
# IMPORTANT: do NOT use --force; do NOT use subtree split; CF Pages needs regular main push
git push origin main 2>&1 | tee -a "${LOG_FILE}"

echo "=== Pipeline complete — CF Pages will auto-build in ~60s ===" | tee -a "${LOG_FILE}"
